/*
 * Map.cpp
 *
 *  Created on: Mar 10, 2014
 *      Author: root
 */

#include "Map.hpp"
//#include "Register.hpp"

#include <iostream>
#include <string>
#include <algorithm>

using namespace std;
namespace sgw {

Map::Map() {
	m_registerListController.insert(m_registerListController.end(), &DesignCapacity);
	m_registerListController.insert(m_registerListController.end(), &DesignVoltage);
	m_registerListController.insert(m_registerListController.end(), &ManufactureDate);
	m_registerListController.insert(m_registerListController.end(), &SerialNumber);
	m_registerListController.insert(m_registerListController.end(), &ManufactureName);
	m_registerListController.insert(m_registerListController.end(), &DeviceName);
	m_registerListController.insert(m_registerListController.end(), &DeviceChemistry);
	m_registerListController.insert(m_registerListController.end(), &ModelName);
	m_registerListController.insert(m_registerListController.end(), &ConnectedModuleInfo);
	m_registerListController.insert(m_registerListController.end(), &ControllerInfo);
	m_registerListController.insert(m_registerListController.end(), &FirmwareVersion);
	m_registerListController.insert(m_registerListController.end(), &Status);
	m_registerListController.insert(m_registerListController.end(), &BatteryStatus);
	m_registerListController.insert(m_registerListController.end(), &Voltage);
	m_registerListController.insert(m_registerListController.end(), &Current);
	m_registerListController.insert(m_registerListController.end(), &SysWarning);
	m_registerListController.insert(m_registerListController.end(), &SysMaxCellVoltage);
	m_registerListController.insert(m_registerListController.end(), &SysMinCellVoltage);
	m_registerListController.insert(m_registerListController.end(), &Temperature);
	m_registerListController.insert(m_registerListController.end(), &RelativeStateOfCharge);
	m_registerListController.insert(m_registerListController.end(), &RemainCapacity);
	m_registerListController.insert(m_registerListController.end(), &FullChargeCapacity);
	m_registerListController.insert(m_registerListController.end(), &AverageCurrent);
	m_registerListController.insert(m_registerListController.end(), &ChargingCurrent);
	m_registerListController.insert(m_registerListController.end(), &ChargingVoltage);
	m_registerListController.insert(m_registerListController.end(), &CycleCount);
	m_registerListController.insert(m_registerListController.end(), &HeaterStatus);
	m_registerListController.insert(m_registerListController.end(), &FanStatus);
	m_registerListController.insert(m_registerListController.end(), &SysMaxCellTemp);
	m_registerListController.insert(m_registerListController.end(), &SysMinCellTemp);
	m_registerListController.insert(m_registerListController.end(), &HeatsinkTemperature);
	m_registerListController.insert(m_registerListController.end(), &IGBTControl);
	m_registerListController.insert(m_registerListController.end(), &IGBTStatus);

	// Modules:
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_0);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_0);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_0);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_0);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_0);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_0);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_0);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_0);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_0);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_0);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_0);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_0);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfol_1);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_1);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_1);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_1);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_1);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_1);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_1);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_1);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_1);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_1);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_1);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_1);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_2);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_2);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_2);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_2);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_2);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_2);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_2);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_2);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_2);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_2);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_2);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_2);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_3);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_3);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_3);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_3);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_3);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_3);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_3);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_3);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_3);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_3);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_3);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_3);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_4);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_4);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_4);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_4);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_4);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_4);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_4);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_4);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_4);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_4);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_4);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_4);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_5);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_5);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_5);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_5);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_5);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_5);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_5);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_5);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_5);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_5);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_5);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_5);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_6);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_6);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_6);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_6);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_6);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_6);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_6);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_6);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_6);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_6);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_6);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_6);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_7);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_7);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_7);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_7);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_7);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_7);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_7);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_7);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_7);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_7);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_7);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_7);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_8);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_8);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_8);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_8);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_8);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_8);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_8);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_8);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_8);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_8);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_8);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_8);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_9);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_9);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_9);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_9);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_9);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_9);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_9);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_9);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_9);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_9);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_9);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_9);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_10);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_10);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_10);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_10);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_10);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_10);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_10);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_10);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_10);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_10);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_10);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_10);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_11);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_11);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_11);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_11);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_11);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_11);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_11);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_11);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_11);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_11);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_11);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_11);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_12);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_12);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_12);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_12);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_12);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_12);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_12);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_12);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_12);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_12);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_12);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_12);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_13);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_13);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_13);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_13);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_13);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_13);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_13);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_13);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_13);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_13);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_13);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_13);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_14);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_14);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_14);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_14);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_14);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_14);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_14);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_14);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_14);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_14);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_14);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_14);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleInfo_15);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellVoltage_15);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellVoltage_15);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleStatus_15);
	m_registerListModule.insert(m_registerListModule.end(), &Alarm_15);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleVoltage_15);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCurrent_15);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleSOC_15);
	m_registerListModule.insert(m_registerListModule.end(), &MaxCellTemp_15);
	m_registerListModule.insert(m_registerListModule.end(), &MinCellTemp_15);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleTemperature_15);
	m_registerListModule.insert(m_registerListModule.end(), &ModuleCycleCount_15);

}

Map::~Map() {
	// TODO Auto-generated destructor stub
}

} /* namespace sgw */
